language: node_js

node_js:
  - stable

env:
  global:
  - secure: OQK8b8/rmQsQ7kIr2++z12drfmdscfoLW5AgH+IMgf6mEESpd30JbTWQ22sJQWKep5hUiAwolfe7DJX6vjDh8NxehPkdn+L3Ktj0aFcdHfyDqeYKpyvBX4UJue3RgTohRN0aTLH3tBf84DGPPHH1qBnIachhn2dt2QGv8xLrLwHvedobAR7Car4YE41pAHC3vcXltpEbFLPftyghRfVWNYVTBi/jTtGkOXo+4QizvkyBVAeOonvYby2veIfyDuKJivWnKXNXj6w+UYiYKTammcbXeFoakXGz4IZ3wvSnB4XsusYYHA2Wyz1PEeRH0z6d4j015vtUKJJSuBx6S1UugtTfp6OGOYzbkCF466B/6Z6BFqlEQDc58gnAjzXVqrIVOEybkQem3odcWTKQUcWT9PdnnKElNo+ygqIdrFhJ+G2GvBZ0EWHgKxnAx6i+MuyrEFkKrBbdQ4h/3pxm4RfNhSvkp3BJjCtbA9LGHtpPcvavXAd6Q3WGOAgx9ApmxRXR7TbgWfsSqIUlI0mJUlxvMKNOiX9wSC53DG+xOfXzCKCFLLkiX7HUKC1SWybK1BchX9QFe7KTQ4xZQEYawEDT6IWYpF62+V2C5ICcUv97tbLkrkRYx26DlZBwX9EqVLZGfPAB8Qf/F2a+Q8CUSoN+ZzvtHKtc8SGEX7SF6+Mtpps=
  - secure: aN/owraa2j0zHmfKLj3dA0OBs5Mh15HZZk3/hQ5adBiNN0CzFN0ePUvYt+4K9W7Ea6/jRrq62RiMaaPnY4CHAKoG7DoRTlgxygTts8T4f46vgzd+S3k5jffs9ZQcKqBhMJWTh4ZFh39C92Yfy9QOOu90mkMWh0v0n+jNZ9UlfVt6sJnqU9iOZo2gSjRhy3gXmGgBo3YDWUqc0goxhVbsaovZkgulOVz4FsaIy75CN6JzdM/VcgMIMWMcWZ85SLEV+z/+WVYmVUpAn15PjlwoWsybmsmWyHHbdOM+RCD37uRlGLR3b6qhrzKPsZToXrkWoc+3jz83cJG1Q3ms2DMP5zpEmKQjqNtTIJCqmKje0DhfByS5gduJma3z1Q8ToPNy98p9Pgad2DsV4PPtlLsp2GG5J6yhBwSsLy9HLhSKbJM3LanHVMgykkKoT8+RD4igS/awWIrE1/y8Txfz6cccehhA8FY1AmVRNqbZg7UcffVJiJt4prdPb6Ww1RDeu2QZlQmn+FXKzX0nUf8EbAXwpqt2hOYya+ftY9T/DvMMzH0WHP0Nd1Y/A2U4MEyMxSyyxalnDlKBQcvj/RiAhbZ3cP3OASdetmkC5cmhkwO76yMEDh9dHWeeK7/giQQYG4lIQ0BoGtUFoQp/6cdWsCKauni0zkQ4UrJV3w2CTwBdOzQ=

before_script:
  - bower install

after_success:
  - npm run-script coveralls
